In [9]:
import numpy as np
import pandas as pd

In [11]:
data=pd.read_csv("LinearRegressionWithMultipalRegression(homeprice).csv")

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      6 non-null      int64  
 1   bedrooms  5 non-null      float64
 2   age       6 non-null      int64  
 3   price     6 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 324.0 bytes


In [19]:
median_bedrooms=np.mean(data['bedrooms'])
data.bedrooms.fillna(median_bedrooms,inplace=True)

C:\Users\Acer\AppData\Local\Temp\ipykernel_9104\734752960.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data.bedrooms.fillna(median_bedrooms,inplace=True)


In [21]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.2   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [23]:
x=data.iloc[:,0:2].values
y=data.iloc[:,3].values

array([[2.6e+03, 3.0e+00],
       [3.0e+03, 4.0e+00],
       [3.2e+03, 4.2e+00],
       [3.6e+03, 3.0e+00],
       [4.0e+03, 5.0e+00],
       [4.1e+03, 6.0e+00]])

In [25]:
y=data.iloc[:,3].values

In [27]:
y

array([550000, 565000, 610000, 595000, 760000, 810000], dtype=int64)

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [60]:
class GDRegressor:
    def _init_ (self,learning_rate=0.1,epochs=50 ):
        self.lr=learning_rate
        self.coef_=None
        self.intercept=None

    def fit(self,x_train,y_train,learning_rate=0.1):
        # to find intercept
        self.intercept=0;
        self.coef_=np.ones(x_train.shape[1])
        for i in range(x_train.shape[0]):
            y=np.dot(x_train,self.coef_)+self.intercept
            slop_intercept=(-2)*(np.mean(y_train-y))
            self.intercept=self.intercept-learning_rate*slop_intercept
            slope_coef=-2*np.dot((y_train-y),x_train)/x_train.shape[0]
            self.coef_=self.coef_-slope_coef*learning_rate
    
        print(self.intercept,self.coef_)         
    
    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept
        


In [62]:
abc=GDRegressor()

In [64]:
abc.fit(x_train,y_train)

-1.6238365829601218e+24 [-5.62569169e+27 -6.81289711e+24]


In [66]:
y_pabc.predict(x_train)

array([-2.02525122e+31, -1.80022437e+31, -2.30653784e+31, -1.46268205e+31])

In [70]:
y_train

array([595000, 610000, 810000, 550000], dtype=int64)

In [72]:
from sklearn.metrics import mean_absolute_error,mean_squared_error ,r2_score

In [78]:
print("R2 score",r2_score(predict,y_test))

NameError: name 'predict' is not defined